CREATE TABLE professores (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            varchar(120) NOT NULL,
    cpf             varchar(14) UNIQUE,
    endereco        varchar(255),
    dt_nascimento   date,
    telefone        varchar(20),
    email           varchar(120),
    registro        varchar(20) UNIQUE,
    titulacao       varchar(60),
    regime_trabalho varchar(10)
);

CREATE TABLE cursos (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              varchar(120) NOT NULL,
    ch_total          integer NOT NULL,
    prev_termino_anos integer NOT NULL,
    limite_conclusao  integer NOT NULL,
    coordenador_id    bigint,
    CONSTRAINT fk_curso_coord FOREIGN KEY (coordenador_id) REFERENCES professores (id)
);

CREATE TABLE alunos (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          varchar(120) NOT NULL,
    cpf           varchar(14) UNIQUE,
    endereco      varchar(255),
    dt_nascimento date,
    telefone      varchar(20),
    email         varchar(120),
    matricula_id  integer NOT NULL UNIQUE,
    turno         varchar(10),
    nec_especial  varchar(255),
    curso_id      bigint,
    CONSTRAINT fk_aluno_curso FOREIGN KEY (curso_id) REFERENCES cursos (id),
    CONSTRAINT chk_aluno_turno CHECK (turno IS NULL OR turno IN ('MANHA', 'TARDE', 'NOITE', 'INTEGRAL'))
);

CREATE TABLE disciplinas (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo           varchar(10) NOT NULL UNIQUE,
    nome             varchar(120) NOT NULL,
    creditos         integer NOT NULL,
    ch               integer NOT NULL,
    ementa           text,
    modalidade       varchar(10),
    curso_id         bigint NOT NULL,
    ativo            smallint DEFAULT 1 NOT NULL,
    pre_requisito_id bigint,
    CONSTRAINT fk_disciplina_curso FOREIGN KEY (curso_id) REFERENCES cursos (id),
    CONSTRAINT fk_disciplina_pre_req FOREIGN KEY (pre_requisito_id) REFERENCES disciplinas (id),
    CONSTRAINT chk_disciplina_modalidade CHECK (modalidade IS NULL OR modalidade IN ('PRESENCIAL', 'EAD', 'HIBRIDA')),
    CONSTRAINT chk_disciplina_ativo CHECK (ativo IN (0, 1))
);

CREATE TABLE turmas (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        varchar(30) NOT NULL UNIQUE,
    horario       varchar(30),
    vagas         integer NOT NULL,
    carga_horaria integer,
    semestre      varchar(10) NOT NULL,
    ano           integer NOT NULL,
    turno         varchar(10),
    sala          varchar(20),
    status        varchar(15) DEFAULT 'OPEN' NOT NULL,
    ativo         smallint DEFAULT 1 NOT NULL,
    professor_id  bigint,
    disciplina_id bigint,
    CONSTRAINT fk_turma_professor FOREIGN KEY (professor_id) REFERENCES professores (id),
    CONSTRAINT fk_turma_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id),
    CONSTRAINT chk_turma_vagas CHECK (vagas >= 0),
    CONSTRAINT chk_turma_turno CHECK (turno IS NULL OR turno IN ('MANHA', 'TARDE', 'NOITE', 'INTEGRAL')),
    CONSTRAINT chk_turma_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'CLOSED')),
    CONSTRAINT chk_turma_ativo CHECK (ativo IN (0, 1))
);

CREATE TABLE matriculas_em_turma (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id     bigint NOT NULL,
    turma_id     bigint NOT NULL,
    dt_inscricao date DEFAULT CURRENT_DATE NOT NULL,
    situacao     varchar(12) DEFAULT 'ATIVA' NOT NULL,
    frequencia   numeric(5, 2) DEFAULT 0 NOT NULL,
    media_final  numeric(4, 2),
    observacao   varchar(500),
    CONSTRAINT fk_matricula_aluno FOREIGN KEY (aluno_id) REFERENCES alunos (id),
    CONSTRAINT fk_matricula_turma FOREIGN KEY (turma_id) REFERENCES turmas (id),
    CONSTRAINT uq_aluno_turma UNIQUE (aluno_id, turma_id),
    CONSTRAINT chk_matricula_situacao CHECK (situacao IN ('ATIVA', 'TRANCADA', 'CONCLUIDA', 'REPROVADA')),
    CONSTRAINT chk_matricula_frequencia CHECK (frequencia BETWEEN 0 AND 100),
    CONSTRAINT chk_matricula_media_final CHECK (media_final IS NULL OR media_final BETWEEN 0 AND 10)
);

CREATE TABLE provas (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo   varchar(40) NOT NULL UNIQUE,
    peso     numeric(4, 2) NOT NULL,
    conteudo text,
    turma_id bigint NOT NULL,
    CONSTRAINT fk_prova_turma FOREIGN KEY (turma_id) REFERENCES turmas (id),
    CONSTRAINT chk_prova_peso CHECK (peso > 0)
);

CREATE TABLE resultados_prova (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id    bigint NOT NULL,
    prova_id        bigint NOT NULL,
    nota            numeric(4, 2),
    presente        smallint DEFAULT 0,
    data_realizacao date,
    duracao_min     integer,
    CONSTRAINT fk_resultado_matricula FOREIGN KEY (matricula_id) REFERENCES matriculas_em_turma (id),
    CONSTRAINT fk_resultado_prova FOREIGN KEY (prova_id) REFERENCES provas (id),
    CONSTRAINT uq_matricula_prova UNIQUE (matricula_id, prova_id),
    CONSTRAINT chk_resultado_nota CHECK (nota IS NULL OR nota BETWEEN 0 AND 10),
    CONSTRAINT chk_resultado_presente CHECK (presente IS NULL OR presente IN (0, 1))
);

CREATE TABLE usuarios_sistema (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login      varchar(50) NOT NULL UNIQUE,
    senha_hash varchar(60) NOT NULL,
    perfil     varchar(15) NOT NULL,
    pessoa_id  bigint,
    ativo      boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_usuario_perfil CHECK (perfil IN ('SECRETARIA', 'DIRETOR', 'COORDENADOR', 'PROFESSOR', 'ALUNO', 'ADMIN')),
    CONSTRAINT chk_usuario_ativo_true CHECK (ativo IN (true, false))
);

CREATE INDEX idx_curso_coord ON cursos (coordenador_id);
CREATE INDEX idx_aluno_curso ON alunos (curso_id);
CREATE INDEX idx_disc_curso ON disciplinas (curso_id);
CREATE INDEX idx_disc_pre_req ON disciplinas (pre_requisito_id);
CREATE INDEX idx_turma_professor ON turmas (professor_id);
CREATE INDEX idx_turma_disc ON turmas (disciplina_id);
CREATE INDEX idx_mat_aluno ON matriculas_em_turma (aluno_id);
CREATE INDEX idx_mat_turma ON matriculas_em_turma (turma_id);
CREATE INDEX idx_res_matricula ON resultados_prova (matricula_id);
CREATE INDEX idx_res_prova ON resultados_prova (prova_id);
